# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                  provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                  remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)

                  always_use_default_target_path: false
                  use_referer: true
                  default_target_path: /user/accueil
                  success_handler: redirect.after.login



            logout:

                            path: /logout
                            target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }



