<?php

namespace CRA\AdminBundle\Repository;

/**
 * absenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class absenceRepository extends \Doctrine\ORM\EntityRepository
{
}
