<?php

namespace CRA\AdminBundle\Repository;

/**
 * cramoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cramoisRepository extends \Doctrine\ORM\EntityRepository
{
}
