<?php

namespace CRA\AdminBundle\Repository;

/**
 * projetmoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projetmoisRepository extends \Doctrine\ORM\EntityRepository
{
}
